language: python
python:
    - "2.7"
    - "3.4"
env:
    global:
        - COVERALLS_PARALLEL=true

    matrix:
    - PYSAM_VERSION=0.8.4
    - PYSAM_VERSION=0.9.0

before_install:
    - wget -nd -nc -r -l1  -A'*0.8.4*.whl' --execute robots=off http://www.cgat.org/downloads/public/pysam/wheels/
    - wget -nd -nc -r -l1  -A'*0.9.0*.whl' --execute robots=off http://www.cgat.org/downloads/public/pysam/wheels/

install:
    - pip install `grep cython requirements.txt`
    - pip install -vvv --use-wheel --find-links=./ pysam==$PYSAM_VERSION
    - pip install -r requirements.txt
    - pip install coverage
    - pip install coveralls

script:
    - nosetests --with-coverage --verbose --cover-package=connor
#    - nosetests examples

after_success:
    - coveralls

notifications:
    webhooks: https://coveralls.io/webhook?repo_token=gjCJEFWDp80kULHoFUZph5PQekEtFDCDj
    email:
        - bfx-connor@umich.edu

