language: python
python:
    - "2.7"
    - "3.4"
env:
    global:
        - CODECLIMATE_REPO_TOKEN=5684ebe19ec80ce9b4a8cfeab8c6d4e5a5ecc31e264d43bacee8e5050e07224b
    matrix:
    - PYSAM_VERSION=0.8.4
    - PYSAM_VERSION=0.9.0

before_install:
    - wget -nd -nc -r -l1  -A'*0.8.4*.whl' --execute robots=off http://www.cgat.org/downloads/public/pysam/wheels/
    - wget -nd -nc -r -l1  -A'*0.9.0*.whl' --execute robots=off http://www.cgat.org/downloads/public/pysam/wheels/

install:
    - pip install `grep cython requirements.txt`
    - pip install -vvv --use-wheel --find-links=./ pysam==$PYSAM_VERSION
    - pip install -r requirements.txt
    - pip install coverage
    - pip install codeclimate-test-reporter

script:
    - nosetests --with-coverage --verbose --cover-package=connor
#    - nosetests examples

after_success:
    - codeclimate-test-reporter

notifications:
    email:
        - cgates@umich.edu, pulintz@umich.edu

