language: python
python:
    - "2.7"
    - "3.4"
env:
    matrix:
        - PYSAM_VERSION=0.8.4
	- PYSAM_VERSION=0.9.0

install:
    - pip install -q pysam==$PYSAM_VERSION
    - pip install -q -r requirements.txt

script:
    - nosetests --with-coverage --verbose --cover-package=connor

notifications:
    email:
        - bfx-connor@umich.edu

